stage: rank 
model_ckpt_path: saved_model_demo/ranker_best_ckpt
feature_cache_config_path: inference/feature_insert/feature_cache_configs/recflow_feature_cache_config.yaml
inference_dataset_path: inference/inference_data/recflow/recflow_infer_data.feather
candidates_path: inference/inference_data/recflow/candidates_demo.feather
output_topk: 10
request_features: ['user_id', 'request_timestamp']
output_save_path: inference/inference_data/recflow/ranker_outputs.feather
infer_batch_size: 128
infer_device: 0